import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import nodemailer from "npm:nodemailer@6.9.16";
const headers={"Content-Type":"application/json"}; type Row=Record<string,any>;
async function sha256(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function nm(r:Row={}){return `${r.first_name||""} ${r.last_name||""}`.trim()||String(r.employee_code||"").trim();}
function day(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=(x:string)=>p.find(y=>y.type===x)?.value||"00";return `${g("year")}-${g("month")}-${g("day")}`;}
Deno.serve(async(req:Request)=>{try{
 if(req.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405,headers});
 const token=req.headers.get("X-QCMS-Scheduler")||"";if(!token)return new Response(JSON.stringify({error:"Scheduler token required"}),{status:401,headers});
 const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const th=await sha256(token);
 const {data:cfg=[]}=await admin.from("qcms_notification_scheduler_config").select("tenant_id,scheduler_token_hash");const tenants=cfg.filter((r:Row)=>String(r.scheduler_token_hash)===th).map((r:Row)=>String(r.tenant_id));if(!tenants.length)return new Response(JSON.stringify({error:"Invalid scheduler token"}),{status:401,headers});
 let sent=0,skipped=0,failed=0;const today=day();
 for(const tenantId of tenants){
  const [{data:settings},{data:pos=[]},{data:employees=[]},{data:routes=[]},{data:parties=[]}]=await Promise.all([
   admin.from("qcms_email_settings").select("*").eq("tenant_id",tenantId).maybeSingle(),
   admin.from("supply_purchase_orders").select("id,po_number,supplier_id,submitted_at,created_at,submitted_by_employee_id,approval_status,status").eq("tenant_id",tenantId).eq("approval_status","PENDING_APPROVAL").limit(5000),
   admin.from("employees").select("id,employee_code,first_name,last_name,email,department,reports_to_employee_id,status").eq("tenant_id",tenantId).eq("status","ACTIVE").limit(5000),
   admin.from("qcms_module_approval_routes").select("id,module_key,department,level_no,level_name,employee_id,required,status,overdue_after_hours,overdue_after_days,notify_overdue").eq("tenant_id",tenantId).eq("module_key","SUPPLY_CHAIN").eq("status","ACTIVE").limit(500),
   admin.from("parties").select("id,party_name,party_code").eq("tenant_id",tenantId).limit(5000)]);
  if(!settings?.enabled||!settings?.smtp_host||!settings?.sender_email)continue;
  const em=new Map<string,Row>(employees.map((r:Row)=>[String(r.id),r]));const pm=new Map<string,Row>(parties.map((r:Row)=>[String(r.id),r]));
  const tr=nodemailer.createTransport({host:settings.smtp_host,port:Number(settings.smtp_port||587),secure:Boolean(settings.use_ssl),requireTLS:Boolean(settings.use_tls)&&!Boolean(settings.use_ssl),auth:settings.smtp_username?{user:settings.smtp_username,pass:settings.smtp_password||""}:undefined,connectionTimeout:Number(settings.timeout_seconds||20)*1000});
  for(const po of pos){if(String(po.status||"").toUpperCase()==="CANCELLED")continue;const sm=Date.parse(String(po.submitted_at||po.created_at||""));if(!Number.isFinite(sm)){skipped++;continue;}const hrs=Math.max(0,(Date.now()-sm)/3600000);const sub=em.get(String(po.submitted_by_employee_id||""))||{};const dept=String(sub.department||"").trim().toLowerCase();
   let cand=routes.filter((r:Row)=>Boolean(r.required)&&r.employee_id&&Boolean(r.notify_overdue??true)&&(!r.department||String(r.department).trim().toLowerCase()===dept)).sort((a:Row,b:Row)=>{const ap=a.department?0:1,bp=b.department?0:1;return ap!==bp?ap-bp:Number(a.level_no||1)-Number(b.level_no||1)});
   if(!cand.length&&sub.reports_to_employee_id)cand=[{level_no:1,level_name:"Manager Approval",employee_id:sub.reports_to_employee_id,overdue_after_hours:24,notify_overdue:true}];
   for(const route of cand){const threshold=Math.max(1,Number(route.overdue_after_hours||0)||Number(route.overdue_after_days||0)*24||(Number(route.level_no||1)===1?24:48));if(hrs<threshold){skipped++;continue;}const person=em.get(String(route.employee_id||""))||{};const email=String(person.email||"").trim();if(!email.includes("@")){skipped++;continue;}const ln=Number(route.level_no||1),lname=String(route.level_name||`Approval Level ${ln}`),dedupe=`PO_APPROVAL_OVERDUE:${today}:${po.id}:L${ln}:${email.toLowerCase()}`;const {data:ex}=await admin.from("qcms_notification_outbox").select("id").eq("tenant_id",tenantId).eq("dedupe_key",dedupe).maybeSingle();if(ex?.id){skipped++;continue;}const sup=pm.get(String(po.supplier_id||""))||{};const subject=`QCMS · ${ln>1?"ESCALATION · ":""}PO ${po.po_number||"-"} approval overdue`;const body=[`Purchase Order ${po.po_number||"-"} is pending approval for ${Math.floor(hrs)} hours.`,`Supplier: ${sup.party_name||sup.party_code||"-"}`,`Approval level: ${lname}`,`Responsible employee: ${nm(person)||email}`,`Submitted by: ${nm(sub)||"-"}`,`Overdue threshold: ${threshold} hours`,ln>1?`This is an automatic Level-${ln} escalation.`:"Please review and approve/reject the PO in QCMS."].join("\n");const esc=body.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
    const {data:outbox,error:ie}=await admin.from("qcms_notification_outbox").insert({tenant_id:tenantId,event_key:"PO_APPROVAL_OVERDUE",recipient_email:email,recipient_name:nm(person)||null,subject,body_text:body,body_html:`<div style="font-family:Arial;white-space:pre-line">${esc}</div>`,context:{po_id:po.id,po_number:po.po_number,approval_level:lname,approval_level_no:ln,hours_pending:Math.floor(hrs),overdue_after_hours:threshold,responsible_employee_id:route.employee_id},template_key:"PO_PENDING_APPROVAL",dedupe_key:dedupe,is_automatic:true,scheduled_for:new Date().toISOString(),status:"PENDING"}).select("*").single();if(ie)throw ie;
    try{await admin.from("qcms_notification_outbox").update({status:"SENDING",attempts:1,updated_at:new Date().toISOString()}).eq("id",outbox.id);await tr.sendMail({from:settings.sender_name?`"${String(settings.sender_name).replaceAll('"','')}" <${settings.sender_email}>`:settings.sender_email,to:nm(person)?`"${nm(person).replaceAll('"','')}" <${email}>`:email,subject,text:body,html:`<div style="font-family:Arial;white-space:pre-line">${esc}</div>`});await admin.from("qcms_notification_outbox").update({status:"SENT",sent_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq("id",outbox.id);sent++;}catch(e){const m=e instanceof Error?e.message:String(e);await admin.from("qcms_notification_outbox").update({status:"FAILED",last_error:m.slice(0,2000),updated_at:new Date().toISOString()}).eq("id",outbox.id);failed++;}
   }
  }
 }
 return new Response(JSON.stringify({sent,skipped,failed}),{headers});
}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:String(e)}),{status:500,headers});}});
