from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
required = [
    "streamlit_app.py",
    "requirements.txt",
    ".streamlit/config.toml",
    ".streamlit/secrets.toml.example",
    ".github/workflows/quality-checks.yml",
    "portal/app_registry.toml",
    "portal/portal_contract.json",
    "supabase/config.toml",
    "supabase/migrations/20260802043000_qsms_focused_v430.sql",
    "supabase/migrations/20260802043100_qsms_multi_part_rmtc.sql",
    "supabase/migrations/20260802043200_qsms_not_applicable.sql",
    "supabase/migrations/20260802065000_qsms_inspection_workflow_v460.sql",
    "supabase/migrations/20260802065100_qsms_inspection_delete_and_sequences_v460.sql",
    "supabase/migrations/20260802090000_qsms_rmtc_reliability_v472.sql",
    "supabase/migrations/20260802112000_qsms_rmtc_workflow_admin_v473.sql",
    "supabase/migrations/20260802133000_qsms_steel_production_layout_v480.sql",
    "supabase/migrations/20260802133100_qsms_steel_production_allocation_guard_v480.sql",
    "supabase/migrations/20260802150000_qsms_heat_production_microstructure_v481.sql",
    "supabase/migrations/20260802172000_qsms_heat_search_global_steel_v483.sql",
    "supabase/migrations/20260802193000_qsms_unified_records_v484.sql",
    "supabase/migrations/20260802201500_qsms_combined_heat_balance_v485.sql",
    "app_pages/records_center.py",
    "tests/test_v484_unified_records.py",
    "tests/test_v485_combined_heat_balance.py",
    "supabase/migrations/20260802213000_qsms_heat_supplier_rmtc_ledger_v486.sql",
    "tests/test_v486_heat_supplier_rmtc_ledger.py",
    "core/steel_balance.py",
    "tests/test_v483_heat_search_global_steel.py",
    "tests/test_v481_heat_production_microstructure.py",
    "templates/RMTC_Entry_Template.xlsx",
    "templates/Material_Inward_Template.xlsx",
    "templates/MetLAB_Report_Layout_Template.xlsx",
    "app_pages/inspection_layouts.py",
    "app_pages/dimensional_report.py",
    "app_pages/metlab_report.py",
    "data/Dimensional Report.xlsx",
    "core/osp_service.py",
    "app_pages/osp_transactions.py",
    "app_pages/osp_inspections.py",
    "supabase/migrations/20260803231000_qsms_osp_transactions_v490.sql",
    "tests/test_v490_osp_transactions.py",
    "docs/RELEASE_4_9_0.md",
    "app_pages/reports.py",
    "supabase/migrations/20260805084500_qsms_osp_parameter_groups_reports_v491.sql",
    "tests/test_v491_osp_parameter_groups_reports.py",
    "docs/RELEASE_4_9_1.md",
    "app_pages/process_master.py",
    "core/reporting.py",
    "supabase/migrations/20260805194500_qsms_simplified_metlab_process_master_print_v492.sql",
    "tests/test_v492_simplified_metlab_process_master_print.py",
    "docs/RELEASE_4_9_2.md",
    "supabase/migrations/20260811090000_qcms_rmtc_microstructure_print_reports_v496.sql",
    "tests/test_v496_qcms_global_heat_print_reports.py",
    "docs/RELEASE_4_9_6.md",
    "app_pages/master_import.py",
    "app_pages/my_account.py",
    "supabase/migrations/20260812113000_qcms_universal_delete_account_import_print_v4100.sql",
    "tests/test_v4100_universal_delete_account_import_npd_photos.py",
    "docs/RELEASE_4_10_0.md",
    "app_pages/standards_bank.py",
    "core/selection_labels.py",
    "templates/Customer_Standards_Template.xlsx",
    "supabase/migrations/20260812130000_qcms_customer_standards_selection_cards_v4101.sql",
    "tests/test_v4101_customer_standards_selection_npd_cards.py",
    "docs/RELEASE_4_10_1.md",
    "supabase/migrations/20260812184500_qcms_admin_standard_unlink_readability_v4103.sql",
    "tests/test_v4103_standard_visibility_admin_unlink_fonts.py",
    "docs/RELEASE_4_10_3.md",
]
missing = [path for path in required if not (ROOT / path).exists()]
secrets = ROOT / ".streamlit" / "secrets.toml"
report = {
    "phase": "QCMS 4.10.4 - RMTC numeric stability and premium login workspace",
    "required_files": len(required),
    "missing": missing,
    "local_secrets_present": secrets.exists(),
    "project_ref_configured": "xxrxopzxzyjnzumrwuwy" in (ROOT / "supabase" / "config.toml").read_text(encoding="utf-8"),
    "portal_contract_present": (ROOT / "portal" / "portal_contract.json").exists(),
}
print(json.dumps(report, indent=2))
raise SystemExit(1 if missing else 0)
