plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fourstar.qcms'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fourstar.qcms'
        minSdk 26
        targetSdk 35
        versionCode 18
        versionName '1.0.2'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.test'
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
