[theme]
base = "light"
primaryColor = "#315F79"
backgroundColor = "#F1F3F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E2A33"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
maxUploadSize = 40
