[theme]
base = "light"
primaryColor = "#0F8B8D"
backgroundColor = "#F1F6F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#173233"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
maxUploadSize = 40
